# Generated by Django 2.0.2 on 2018-02-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images'),
        ),
    ]
