# Generated by Django 2.0.2 on 2018-02-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=3, default=11.5, max_digits=5),
            preserve_default=False,
        ),
    ]
