# Generated by Django 2.0.2 on 2018-03-01 17:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0008_auto_20180301_1501'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fav_Rest',
            new_name='FavRest',
        ),
    ]
